//*****************************************************************************
//	Author: Ben Maxey
//
//	Lagrange2D evaluates the interpolating polynomial generated by the given
//	nodes and function values at the specified point.  The Matrix x holds the x
//	nodes, y holds the y nodes, f holds the values at each node, and (a,b) is
//	the evaluation point.
//*****************************************************************************

#ifndef LAGRANGE_2D_H
#define LAGRANGE_2D_H

#include "matrix.hpp"

double Lagrange2D(Matrix& x, Matrix& y, Matrix& f, double a, double b);

#endif